export const currencyData = {
    usd: { flag: require('./assets/flags/us.png'), name: "US Dollar" },
    eur: { flag: require('./assets/flags/eu.png'), name: "Euro" },
    gbp: { flag: require('./assets/flags/gb.png'), name: "British Pound" },
    chf: { flag: require('./assets/flags/ch.png'), name: "Swiss Franc" },
    cad: { flag: require('./assets/flags/ca.png'), name: "Canadian Dollar" },
    aud: { flag: require('./assets/flags/au.png'), name: "Australian Dollar" },
    sek: { flag: require('./assets/flags/se.png'), name: "Swedish Krona" },
    nok: { flag: require('./assets/flags/no.png'), name: "Norwegian Krone" },
    rub: { flag: require('./assets/flags/ru.png'), name: "Russian Ruble" },
    thb: { flag: require('./assets/flags/th.png'), name: "Thai Baht" },
    sgd: { flag: require('./assets/flags/sg.png'), name: "Singapore Dollar" },
    hkd: { flag: require('./assets/flags/hk.png'), name: "Hong Kong Dollar" },
    azn: { flag: require('./assets/flags/az.png'), name: "Azerbaijani Manat" },
    amd: { flag: require('./assets/flags/am.png'), name: "Armenian Dram" },
    dkk: { flag: require('./assets/flags/dk.png'), name: "Danish Krone" },
    aed: { flag: require('./assets/flags/ae.png'), name: "UAE Dirham" },
    jpy: { flag: require('./assets/flags/jp.png'), name: "Japanese Yen" },
    try: { flag: require('./assets/flags/tr.png'), name: "Turkish Lira" },
    cny: { flag: require('./assets/flags/cn.png'), name: "Chinese Yuan" },
    sar: { flag: require('./assets/flags/sa.png'), name: "Saudi Riyal" },
    inr: { flag: require('./assets/flags/in.png'), name: "Indian Rupee" },
    myr: { flag: require('./assets/flags/my.png'), name: "Malaysian Ringgit" },
    afn: { flag: require('./assets/flags/af.png'), name: "Afghan Afghani" },
    kwd: { flag: require('./assets/flags/kw.png'), name: "Kuwaiti Dinar" },
    bhd: { flag: require('./assets/flags/bh.png'), name: "Bahraini Dinar" },
    omr: { flag: require('./assets/flags/om.png'), name: "Omani Rial" },
    qar: { flag: require('./assets/flags/qa.png'), name: "Qatari Riyal" },

    emm: { flag: require('./assets/flags/emm.png'), name: "Emami" },
    azd: { flag: require('./assets/flags/azd.png'), name: "Azadi" },
    nim: { flag: require('./assets/flags/nim.png'), name: "½ Azadi" },
    rob: { flag: require('./assets/flags/rob.png'), name: "¼ Azadi" },
    grmi: { flag: require('./assets/flags/grm.png'), name: "Gerami" },

    grm: { flag: require('./assets/flags/gram.png'), name: "Gold Gram" },
    mql: { flag: require('./assets/flags/mithqal.png'), name: "Mithqal" },
    oz: { flag: require('./assets/flags/ounce.png'), name: "Ounce" },
};


export const flagImages = {
    usd: require('./assets/flags/us.png'),
    eur: require('./assets/flags/eu.png'),
    gbp: require('./assets/flags/gb.png'),
    chf: require('./assets/flags/ch.png'),
    cad: require('./assets/flags/ca.png'),
    aud: require('./assets/flags/au.png'),
    sek: require('./assets/flags/se.png'),
    nok: require('./assets/flags/no.png'),
    rub: require('./assets/flags/ru.png'),
    thb: require('./assets/flags/th.png'),
    sgd: require('./assets/flags/sg.png'),
    hkd: require('./assets/flags/hk.png'),
    azn: require('./assets/flags/az.png'),
    amd: require('./assets/flags/am.png'),
    dkk: require('./assets/flags/dk.png'),
    aed: require('./assets/flags/ae.png'),
    jpy: require('./assets/flags/jp.png'),
    try: require('./assets/flags/tr.png'),
    cny: require('./assets/flags/cn.png'),
    sar: require('./assets/flags/sa.png'),
    inr: require('./assets/flags/in.png'),
    myr: require('./assets/flags/my.png'),
    afn: require('./assets/flags/af.png'),
    kwd: require('./assets/flags/kw.png'),
    bhd: require('./assets/flags/bh.png'),
    omr: require('./assets/flags/om.png'),
    qaq: require('./assets/flags/qa.png'),

    azd: require('./assets/flags/azd.png'),
    emm: require('./assets/flags/emm.png'),
    nim: require('./assets/flags/nim.png'),
    rob: require('./assets/flags/rob.png'),
    grmi: require('./assets/flags/grm.png'),

    grm: require('./assets/flags/gram.png'),
    mql: require('./assets/flags/mithqal.png'),
    oz: require('./assets/flags/ounce.png'),
};
